services:
  - type: web
    name: loto-frontend
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      # !! BU DƏYƏRLƏRİ ÖZ RENDER BACKEND URL-İNİZLƏ ƏVƏZLƏYİN !!
      - key: NEXT_PUBLIC_API_URL
        value: https://loto-backend.onrender.com/api
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://loto-backend.onrender.com
      - key: NODE_VERSION
        value: 20
